# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ctrip_id', models.IntegerField()),
                ('chinese_name', models.CharField(max_length=20)),
            ],
        ),
    ]
